x_obs:
- cluster_name
- leiden
- batch
- color
y_obs:
- n_genes
- n_counts
obs_groupby:
- cluster_name
- leiden
- batch
- color
obs_subset:
- cluster_name
- leiden
- batch
- color
x_var: highly_variable
y_var:
- n_cells
- means
- dispersions
- dispersions_norm
var_groupby: highly_variable
var_subset: highly_variable
layers:
- X
- raw
diffs:
    diff_exp_comps:
    - 0 vs. rest
    - 1 vs. rest
    - 10 vs. rest
    - 11 vs. rest
    - 12 vs. rest
    - 13 vs. rest
    - 14 vs. rest
    - 2 vs. rest
    - 3 vs. rest
    - 4 vs. rest
    - 5 vs. rest
    - 6 vs. rest
    - 7 vs. rest
    - 8 vs. rest
    - 9 vs. rest
    - Cluster_1 vs. rest
    - Cluster_10 vs. rest
    - Cluster_11 vs. rest
    - Cluster_12 vs. rest
    - Cluster_13 vs. rest
    - Cluster_14 vs. rest
    - Cluster_2 vs. rest
    - Cluster_3 vs. rest
    - Cluster_4 vs. rest
    - Cluster_5 vs. rest
    - Cluster_6 vs. rest
    - Cluster_7 vs. rest
    - Cluster_8 vs. rest
    - Cluster_9 vs. rest
    diff_exp_comp_type: grpVrest
    diff_exp_obs_name:
    - cluster_name
    - leiden
    diff_exp_tests:
    - t-test_overestim_var
    - wilcoxon
dimreds:
    obsm:
    - X_pca
    - X_tsne
    varm: PCs
default_factors:
- cluster_name
- leiden
- batch
