x_obs:
- Group
- leiden
y_obs:
- var
- mean
obs_groupby:
- Group
- leiden
obs_subset:
- Group
- leiden
x_var:
- excess_zero_conc
- sig_lasso_coef
y_var:
- mean
- var
var_groupby: highly_variable
var_subset: highly_variable
layers:
- X
- raw
- composition
- raw_comp
diffs:
    diff_exp_comps:
    - 0 vs. rest
    - 1 vs. rest
    - 2 vs. rest
    - 3 vs. rest
    - CONTROL vs. rest
    - LEAN vs. rest
    - OBESE vs. rest
    - OBESE+VLCD vs. rest
    diff_exp_comp_type: grpVrest
    diff_exp_obs_name:
    - Group
    - leiden
    diff_exp_tests:
    - t-test_overestim_var
    - wilcoxon
dimreds:
    obsm:
    - X_pca
    - X_umap
    - comp_X_pca
    - comp_X_umap
    varm:
    - PCs
    - comp_PCs
default_factors:
- Group
- leiden
- Group
