x_obs:
- Is.Reference
- Condition
- Replicate
- Label
y_obs:
- expr_var
- expr_mean
- expr_frac
- sample_ID
- leiden
obs_groupby:
- Is.Reference
- Condition
- Replicate
- Label
obs_subset:
- Is.Reference
- Condition
- Replicate
- Label
x_var: []
y_var:
- expr_geomean
- expr_mean
- expr_var
- expr_frac
var_groupby: []
var_subset: []
diffs:
    diff_exp_comps:
    - g vs. o
    - g vs. y
    - o vs. y
    diff_exp_comp_type: grpVref
    diff_exp_obs_name: Condition
    diff_exp_tests: unknown
dimreds:
    obsm:
    - X_pca
    - X_umap
    - Xsc_pca
    - Xsc_umap
    varm:
    - PCs
    - sc_PCs
default_factors:
- Condition
- Color
- Replicate
